export { Navbar } from './layout/navbar/Navbar'
export { HomePage } from '../pages/HomePage'
export { Exchange } from '../pages/Exchange'
export { CryptoCurrencies } from '../pages/CryptoCurrencies'
export { CryptoDetails } from '../pages/CryptoDetails'
export { News } from '../pages/News'
export { Footer } from './layout/footer/Footer'